name: Auto Commit Daily

on:
  schedule:
    - cron: "0 4 * * *"   # 9:30 AM IST
    - cron: "0 8 * * *"   # 1:30 PM IST
    - cron: "0 12 * * *"  # 5:30 PM IST
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make changes
        run: |
          echo "Update at $(date)" >> data.txt

      - name: Commit & Push
        run: |
          git config user.name "gauravbakliwaldeveloper-alt"
          git config user.email "gauravbakliwaldeveloper@gmail.com"
          git add .
          git commit -m "Auto commit $(date)" || echo "No changes"
          git push
